list: $/frukt/yt/models/ytvideo/columns.yaml
modelClass: Frukt\Yt\Models\YTVideo
title: YTVideos
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'frukt/yt/ytvideos/update/:id'
